# Taxi-v3

Gym provides different game environments which we can plug into our code and train an agent with. The library takes care of the API for providing all the information that our agent requires, like possible actions, score, and current state. We just need to focus on the algorithm part of our agent.

We'll be using the Gym environment called Taxi-v3, which all of the details explained in previous Notebook were pulled from. The objectives, rewards, and actions are all the same.

## 1. Install Gym(nasium)

We need to install Gymnasium first (Gym from OpenAI is no longer supported). Docs: https://gymnasium.farama.org/  

Executing the following should work.

In [4]:
pip install gymnasium


[notice] A new release of pip available: 22.2.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
pip install "gymnasium[all]"

  Using cached mujoco_py-2.1.2.14-py3-none-any.whl (2.4 MB)
  Using cached lz4-4.3.2-cp310-cp310-win_amd64.whl (99 kB)
  Using cached jaxlib-0.4.18-cp310-cp310-win_amd64.whl (46.6 MB)
  Using cached mujoco-2.3.7-cp310-cp310-win_amd64.whl (3.3 MB)
  Using cached moviepy-1.0.3-py3-none-any.whl
  Using cached imageio-2.31.5-py3-none-any.whl (313 kB)
  Using cached Cython-0.29.36-py2.py3-none-any.whl (988 kB)
  Using cached box2d-py-2.3.5.tar.gz (374 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached jax-0.4.18-py3-none-any.whl (1.7 MB)
  Using cached Shimmy-0.2.1-py3-none-any.whl (25 kB)
  Using cached ml_dtypes-0.3.1-cp310-cp310-win_amd64.whl (126 kB)
  Using cached proglog-0.1.10-py3-none-any.whl (6.1 kB)
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
  Using cached imageio_ffmpeg-0.4.9-py3-none-win_amd64.whl (22.6 MB)
  Using cached fasteners-0.19-py3-none-any.whl (18 kB)
  Using cached cffi-1.16.0-cp31

  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Using setuptools (version 63.2.0).
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\Box2D
      copying library\Box2D\Box2D.py -> build\lib.win-amd64-cpython-310\Box2D
      copying library\Box2D\__init__.py -> build\lib.win-amd64-cpython-310\Box2D
      creating build\lib.win-amd64-cpython-310\Box2D\b2
      copying library\Box2D\b2\__init__.py -> build\lib.win-amd64-cpython-310\Box2D\b2
      running build_ext
      building 'Box2D._Box2D' extension
      swigging Box2D\Box2D.i to Box2D\Box2D_wrap.cpp
      swig.exe -python -c++ -IBox2D -small -O -includeall -ignoremissing -w201 -globals b2Globals -outdir library\Box2D -keyword -w511 -D_SWIG_KWARGS -o Box2D\Box2D_wrap.cpp Box2D\Box2D.i
      Box2D\Common\

In [6]:
pip install gymnasium[toy-text]

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


## 2. Gym's interface

Once installed, we can load the game environment and render what it looks like. When we're all done, we can close the rendering an environment with env.close(). This will clear all memory. So only use when you want to start from scratch again.
We can also print the action and state space.

In [7]:
import gymnasium as gym
import time

For now, let's just render the environment for 10 seconds, and close the window again

In [11]:
env = gym.make("Taxi-v3", render_mode="human") # load the game environment
state, info = env.reset() # reset to make sure with start with a randomly chosen start-state

print("Action Space: {}".format(env.action_space)) # 6 different actions we can take - discrete actions, no continuous actions (no 'range') 
print("State Space: {}\n".format(env.observation_space)) # 500 different states

print("Current state: %d" % env.unwrapped.s)

env.render() # visualize the environment - we only need to call render once
time.sleep(10)
env.close()


Action Space: Discrete(6)
State Space: Discrete(500)

Current state: 111


Reminder of our problem:

- The filled square represents the taxi, which is yellow without a passenger and green with a passenger.
- The pipe ("|") represents a wall which the taxi cannot cross.
- R, G, Y, B are the possible pickup and dropoff locations. The blue letter represents the current passenger pick-up location, and the purple letter is the current destination. In the illustration, these colors are reversed.

- As verified by the prints, we have an Action Space of size 6 (south, north, east, west, pickup and dropoff) and a State Space of size 500 (the taxi's location x the passenger's location x the destination location).
- The current state is randomly chosen (a state between 0 and 499).

## 3. Back to our illustration

We can actually take our illustration, encode its state, and give it to the environment to render in Gym.

<img src="./resources/taxi.png" style="height: 350px"/>

Recall that we have the taxi at row 3, column 1, our passenger is at location 2 (=Y) (out of the 4 possible locations), and our destination is location 0 (=R). Using the Taxi-v3 state encoding method, we can do the following:

In [12]:
env = gym.make("Taxi-v3", render_mode="human")
env.reset()

# now, let's manually encode the state
state = env.unwrapped.encode(3, 1, 2, 0) # (taxi row, taxi column, passenger location, destination location)
print("State:", state)

env.unwrapped.s = state

env.render() # visualize the environment - we only need to call render once
time.sleep(10)
env.close()


State: 328


## 4. Initial State - Exercise

Generate the state where the taxi is in the lower right corner. The passenger is in the taxi and the destination is B. What is the color of the taxi right now?

State: 499


## 5. Step-method

The agent performs an action by using the step-method:

```python
state, reward, done, truncated, info = env.step(action)
```

Remember: There are 6 actions (0=south, 1=north, 2=east, 3=west, 4=pickup and 5=dropoff).

The step-method returns:

- state: the new state
- reward: if your action was beneficial or not
- done: indicates if we have successfully picked up and dropped off a passenger, also called one episode
- truncated: is timelimit reached, or agent out of bounds?
- info: additional info such as performance and latency for debugging purposes

Let's go back to the illustrations state and try the different actions.

<img src="./resources/taxi.png" style="height: 250px"/>

First, let's make sure we start in the position like the image, and let's take a step west (to the left). So, we'll hit a wall, and we should receive a penalty for not reaching the destination, and we should remain in the same state (because we hit the wall).

In [14]:
env = gym.make("Taxi-v3", render_mode="human") # load the game environment again
state, info = env.reset() # reset to make sure with a clean env

state = env.unwrapped.encode(3, 1, 2, 0) # (taxi row, taxi column, passenger index, destination index)
print("Initial state:", state)
env.unwrapped.s = state

env.render() # visualize the environment - we only need to call render once
time.sleep(10)
state, reward, done, truncated, info = env.step(3) # go west
time.sleep(10)
env.close()

print("New state: %d, reward: %d" % (state, reward)) # a -1 penalty for every wall hit and the taxi won't move anywhere

Initial state: 328
New state: 328, reward: -1


Now, let's do it again, but go north instead of west. So we won't hit a wall, but still, we haven't reached our destination.

In [15]:
env = gym.make("Taxi-v3", render_mode="human") # load the game environment again
state, info = env.reset() # reset to make sure with a clean env

state = env.unwrapped.encode(3, 1, 2, 0) # (taxi row, taxi column, passenger index, destination index)
print("Initial state:", state)
env.unwrapped.s = state

env.render() # visualize the environment - we only need to call render once
time.sleep(10)
state, reward, done, truncated, info = env.step(1) # go north
time.sleep(10)
done = True

print("New state: %d, reward: %d" % (state, reward)) #
# taxi moves up

Initial state: 328
New state: 228, reward: -1


## 5. Step-method - Exercise

Generate the state again where the taxi is in the lower right corner. The passenger is in the taxi and the destination is B.

Next, carry out the two steps: first drive the taxi to the destination location, and next drop off the passenger. 
Render the environment at each step, print the new state number, the reward and done.

Initial state: 499
New state: 479, reward: -1, done: 0
New state: 475, reward: 20, done: 1


## 6. The Reward Table

When the Taxi environment is created, there is an initial Reward table that's also created, called *P*. **We can think of it like a matrix that has the number of states as rows and the number of actions as columns, i.e. a states × actions matrix**.

Since every state is in this matrix, we can see the default reward values assigned for state 479.

In [18]:
env.unwrapped.s = 479
env.unwrapped.P[479]

{0: [(1.0, 479, -1, False)],
 1: [(1.0, 379, -1, False)],
 2: [(1.0, 499, -1, False)],
 3: [(1.0, 479, -1, False)],
 4: [(1.0, 479, -10, False)],
 5: [(1.0, 475, 20, True)]}

This dictionary has the structure

``
{action: [(probability, nextstate, reward, done)]}.
``

A few things to note:

- The 0-5 corresponds to the actions (south, north, east, west, pickup, dropoff) the taxi can perform at our current state.
- In this environment, the probability of each action is always 1.0.
- The nextstate is the state we would be in if we take the action at this index of the dictionary.
- All the movement actions have a -1 reward, the pickup action has a -10 reward, the dropoff actions has +20 reward in this particular state.
- done is used to tell us when we have successfully dropped off a passenger at the right location (action 5 in this state). Each successful dropoff is the end of an episode

## 7. Solving the environment without Reinforcement Learning

Let's see what will happen if we try to brute-force our way to solving the problem without RL.

We'll create an infinite loop which runs until one passenger reaches one destination (one episode), or in other words, when the received reward is 20. The `env.action_space.sample()` method automatically selects one random action from the set of all possible actions.

Let's see what happens.

In [19]:
env = gym.make("Taxi-v3", render_mode="human") # load the game environment again
state, info = env.reset() # reset to make sure with a clean env

env.unwrapped.s = 328  # set environment to illustration's state

epochs = 0
penalties, reward = 0, 0

frames = [] # for animation

finished = False

while not finished:
    action = env.action_space.sample() 
    state, reward, done, truncated, info = env.step(action)

    if reward == -10:
        penalties += 1

    epochs += 1
    finished = done or truncated
env.close()
    
print("Timesteps taken: {}".format(epochs))
print("Penalties incurred: {}".format(penalties))

Timesteps taken: 200
Penalties incurred: 62


Not good. Our agent takes thousands (?) of timesteps and makes lots of wrong drop offs to deliver just one passenger to the right destination.

This is because we aren't learning from past experience. We can run this over and over, and it will never optimize. **The agent has no memory of which action was best for each state**, which is exactly what Reinforcement Learning will do for us.

## 8. Q-learning

We are going to use a *simple* RL algorithm called Q-learning which will give our agent some memory. Essentially, Q-learning lets the agent use the environment's rewards to learn, over time, the best action to take in a given state.

Therefore the Q-learning algorithm uses a Q-Table. The Q-table is a matrix where we have a row for every state (500) and a column for every action (6). The matrix is first initialized to 0, and then values are updated during training.

<img src="./resources/qtable.png" style="height: 650px"/>

The optimal action at every state is the action with the highest Q-value. So for state 328 the highest value is -1.971 (=North). For state 499 the highest value is 29 (=West). These actions indeed seem to be the best options.

In [23]:
env = gym.make("Taxi-v3", render_mode="human") # load the game environment again
state, info = env.reset() # reset to make sure with a clean env

env.unwrapped.s = 328
env.render()
print("North is best?\n")
time.sleep(5)

env.unwrapped.s = 499
env.render()
print("West is best?")
time.sleep(5)

env.close()



North is best?

West is best?


## 9. Training the Agent


We can now create the training algorithm that will update this Q-table as the agent explores the environment over 100 000 of episodes (of course you don't need to write this algorithm yourself).

BTW: When we create the environment, we will not be rendering it, because this slows us down way too much. Especially in the next section, where we'll be training a q-table. After this training, we'll use the 'human' rendering again.


Next, we'll initialize the Q-table to a 500×6 matrix of zeros.

In [24]:
env = gym.make("Taxi-v3", render_mode="rgb_array")
state, info = env.reset()

In [25]:
import numpy as np
q_table = np.zeros([env.observation_space.n, env.action_space.n])

In [26]:
%%time
"""Training the agent"""

import random
from IPython.display import clear_output

# Hyperparameters
alpha = 0.1
gamma = 0.6
epsilon = 0.1

# For plotting metrics
all_epochs = []
all_penalties = []

for i in range(1, 100001):
    state, info = env.reset()
    epochs, penalties, reward, = 0, 0, 0
    finished = False
    
    while not finished:
        if random.uniform(0, 1) < epsilon:
            action = env.action_space.sample() # Explore action space
        else:
            action = np.argmax(q_table[state]) # Exploit learned values
        next_state, reward, done, truncated, info = env.step(action) 
        finished = done or truncated

        old_value = q_table[state, action]
        next_max = np.max(q_table[next_state])
        
        new_value = (1 - alpha) * old_value + alpha * (reward + gamma * next_max)
        q_table[state, action] = new_value

        if reward == -10:
            penalties += 1

        state = next_state
        epochs += 1
        
    if i % 100 == 0:
        clear_output(wait=True)
        print(f"Episode: {i}")

print("Training finished.\n")

Episode: 100000
Training finished.

CPU times: total: 1min 2s
Wall time: 55.7 s


Now that the Q-table has been established over 100 000 episodes, let's see what the Q-values are for our two states. Are North and West indeed the two most preferable moves for the two states?

In [27]:
print(q_table[328])
print(q_table[499])

[ -2.4077079   -2.27325184  -2.41119495  -2.36186056 -10.68125864
 -11.00277739]
[ 2.82744455  1.55412369  4.58255907 11.         -2.13330103 -2.81133522]


## 10. Evaluating the agent

Let's evaluate the performance of our agent. We don't need to explore actions any further, so now the next action is always selected using the best Q-value. Training is done, so no more balancing between exploration versus exploitation. Only exploit the knowledge gathered so far, in the Q-table.

In [28]:
"""Evaluate agent's performance after Q-learning"""

total_epochs, total_penalties = 0, 0
episodes = 100

for _ in range(episodes):
    state, info = env.reset()
    epochs, penalties, reward = 0, 0, 0
    
    finished = False
    
    while not finished:
        action = np.argmax(q_table[state]) # take the action with the highest q-value
        state, reward, done, truncated, info = env.step(action)
        finished = done or truncated
        if reward == -10:
            penalties += 1

        epochs += 1

    total_penalties += penalties
    total_epochs += epochs

print(f"Results after {episodes} episodes:")
print(f"Average timesteps per episode: {total_epochs / episodes}")
print(f"Average penalties per episode: {total_penalties / episodes}")

Results after 100 episodes:
Average timesteps per episode: 12.95
Average penalties per episode: 0.0


We can see from the evaluation that the agent's performance improved significantly and it incurred no penalties, which means it performed the correct pickup/dropoff actions with 100 different passengers.

## 11. Solving the environment with Reinforcement Learning - Exercise

Now that our agent is trained, we can use our human rendering again, and use our trained q-table to solve the taxi problem with 328 as the initial state (by analogy with section **7. Solving the environment without RL** of this notebook). Print the timesteps taken and penalties incurred. Pretty impressive! No?

Timesteps taken: 12
Penalties incurred: 0


## 12. Solving the environment with RL - Exercise

Solve the problem for these two initial states.

<img src="./resources/taxi1.png" style="height: 300px"/>
<img src="./resources/taxi2.png" style="height: 300px"/>

In [31]:
# solve the problem with the first/second initial state
# so encode the different states, like state = env.encode(row,column,passenger,destiny), and do the same thing: exploit the knowledge from the q-table: go for np.argmax(q_table[state])!



State: 32
Timesteps taken: 15
Penalties incurred: 0
